# Generated by Django 2.1.7 on 2019-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField()),
                ('store', models.CharField(max_length=64)),
                ('purchase_date', models.DateField()),
                ('date_updated', models.DateField()),
                ('total_price', models.FloatField()),
                ('tax', models.FloatField()),
            ],
        ),
    ]
