# Generated by Django 2.1.7 on 2019-04-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_auto_20190410_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
